create table if not exists public.memories (
    id bigint generated by default as identity primary key,
    image_url text not null,
    description text not null,
    memory_date date not null,
    location text not null,
    created_at timestamptz not null default now()
);

alter table public.memories enable row level security;

create policy "Anyone can view memories"
on public.memories for select
to anon
using (true);

create policy "Anyone can add memories"
on public.memories for insert
to anon
with check (true);

insert into storage.buckets (id, name, public)
values ('memory-images', 'memory-images', true)
on conflict (id) do nothing;

create policy "Anyone can upload memory images"
on storage.objects for insert
to anon
with check (bucket_id = 'memory-images');

create policy "Anyone can view memory images"
on storage.objects for select
to anon
using (bucket_id = 'memory-images');